### ISSUE TITLE
Layout 2 diferit pentru tastaturi en-GB

### ISSUE THREAD

**Issue by adaptabi** [SaltwaterC/romanian-programmers-mac#10]
Salut,

Am un `macbook pro mid 2015` cu layout `uk` (`en-GB`)
Din păcate sunt câteva mici neconcordanțe
![image](https://user-images.githubusercontent.com/485535/27844356-e14584bc-6120-11e7-94b9-e86ddc386d7d.png)
Semnul pound `£` nu poate fi făcut, combinația `alt+3` produce `ˆ` iar `shift+3` produce `#` (cum era de așteptat

`±` din stânga lui `1` plus alt produce `~` iar `alt+~` dintre `z` și `shift` produce `|` - la fel ca `|` cel desenat dinainte de enter (pe rândul de jos).

`alt+p` produce `§` deși e desenat pe tasta dinainte de `1` iar alt+acea tastă nu produce nimic

În rest e mult mai bine decât cu tastatura Românească

Mulțumesc

**Comment by SaltwaterC** [comment]
Romanian Pro nu are aranjament pentru UK. Standardul ([SR 13392:2004](https://www.secarica.ro/kbd/kbdro_help_romanian_standard_ro.pdf), vezi README.md) este făcut peste o tastatură standard US. Implementarea a fost făcută pentru a avea pozițiile corecte ale tastelor, deci ignoră pictogramele. După ani de lucrat cu Romanian Pro sub alte platforme, mă aștept de exemplu să am "`~" în stânga lui 1, indiferet de ce vrea Apple să pună acolo.

Apple sunt un pic mai speciali în sensul că nu respectă nici un standard, anume o tastatură UK arată mult mai diferit decât standardul UK. De fapt o tastatură Apple UK arată aproape ca o tastatură standard US cu excepția lui £ drept alt+3 plus tastele din stânga lui 1 și z.

Cel mult îți pot recomanda https://github.com/SaltwaterC/romanian-programmers-mac/tree/non-standard/uk - are în plus caracterul £ care este alt+g - o combinație care nu e folosită în Romanian Pro. alt+p (pound) - precum ai remarcat este deja folosită, alt+q (quid) deasemena, deci am folosit alt+g pentru că e ușor de memorat. GBP este simbolul folosit de către piețele financiare pentru pound sterling. Este aranjamentul pe care personal îl folosesc.
