### ISSUE TITLE
Acces cu CMD dreapta

### ISSUE THREAD

**Issue by cipri-tom** [SaltwaterC/romanian-programmers-mac#11]
Salut!

Mulțumesc pentru că ai făcut asta! Funcționează excelent (după cum vezi 😃 ) și a fost usor de instalat.

Ai putea oare să îmi spui cum aș putea folosi tasta CMD din dreapta în loc de ALT (option) ? Ideea e că deși pe alte platforme se folosește ALT, pe tastaturile Apple tasta CMD e mai comodă, că e mai aproape de space. Pentru ALT (option) chiar tre să îmi rup degetul 😄 

Tre să fie ceva din Ukelele, dar încă nu l-am verificat prea atent.
Multumesc!

**Comment by SaltwaterC** [comment]
Salut,

Ukelele nu face distincția dintre CMD stânga / dreapta sau ALT stânga / dreapta. Nu sunt convis de faptul că se pot mapa diferit. În general, ai nevoie de dreapta pentru ALT+i => î. Personal folosesc degetul mare + arătător. Pentru "Î" folosesc SHIFT+ALT stânga + i. Reciproca e valabilă, pentru "Ă" spre exemplu, folosesc SHIFT+ALT dreapta + a ce ar fi al doilea caz de care te lovești de ALT dreapta.

Cu timpul s-ar putea să te obișnuiești. Ce-i drept, am folosit Romanian Pro vreo 5 ani sub Ubuntu până să revin pe Mac de unde și motivul pentru care am implementat acest proiect. Îmi este ciudat să scriu fără Romanian Pro. Chiar dacă este posibil, o astfel de combinație ar fi publicată separat ca extensie non-standard ce nu corespune cu SR 13392:2004.

**Comment by cipri-tom** [comment]
Mulțumesc pentru răspuns !

Sper să mă obișnuiesc și să nu fac RSI la degetul mare 😄 . Mi se pare destul de greu ALT (pe ambele mâini) fără să-ți ridici mâna de pe tastatură.

Interesant "approach"-ul tău, apăsând cu aceeași mână (ALT+i). Eu prefer cu mâini opuse 😃 .
Mulțumesc pentru sfaturi. mai încerc !

**Comment by cipri-tom** [comment]
Dacă cineva se mai lovește de această problemă, eu folosesc Karabiner Elements pentru a remapa niște taste, și anume, Right Command -> Right Option si vice-versa. Mi-e mai natural ca "alt drepta" să fie lângă SpaceBar.
