### ISSUE TITLE
Sugestie pentru OPTION/ALT din dreapta

### ISSUE THREAD

**Issue by red-lonely-neuron** [SaltwaterC/romanian-programmers-mac#12]
Salut. Conform [acestui document](https://developer.apple.com/library/content/technotes/tn2056/_index.html#//apple_ref/doc/uid/DTS10003085-CH1-SUBSECTION9), s-ar putea folosi OPTION din dreapta pentru ă, ș etc dacă în loc de **anyOption** s-ar folosi **rightOption** în interiorul tagului XML **modifierMap**. Spre exemplu, în **Romanian - Programmers 1.keylayout**, liniile 26 și 32. Apple precizează în documentul acela că multe tastaturi fizice nu fac diferența între tastele de modificare din stânga și cele din dreapta. Ați încercat totuși să folosiți **rightOption**?

**Comment by SaltwaterC** [comment]
Salut. Nu știam de existența acelui document. Ce-i drept, nu m-am stresat prea mult pentru a-l căuta. O sa încerc să modific manual pentru că Ukelele nu are suport pentru rightOption și Key Codes identifică același cod pentru ambele option. Acest lucru nu e valabil pentru Windows (și probabil distribuțiile Linux) pentru că AltGr este de fapt Ctrl+Alt, deci intern combinația funcționează diferit față de macOS, dar scopul era să produc un aranjament identic din punct de vedere funcțional.

**Comment by SaltwaterC** [comment]
Am incercat:

```cat /Library/Keyboard\ Layouts/Romanian\ -\ Programmers.keylayout | grep Option
			<modifier keys="rightOption"/>
			<modifier keys="anyShift caps? rightOption"/>
			<modifier keys="anyShift? caps? rightOption? command? anyControl"/>
			<modifier keys="caps rightOption"/>
			<modifier keys="anyShift caps rightOption"/>```

Din pacate, nu mai functioneaza deloc. Precum se poate observa, acum scriu fara diacritice, desi folosesc toate combinatiile asa cum sunt invatat. Se pare ca este probabil singura problema care nu poate fi rezolvata sub macOS din moment ce din punct de vedere hardware, tastele Option sunt identice. `rightOption` cred ca este rezervat pentru tastaturi care nu sunt produse de Apple unde Alt si AltGr sunt diferite.
