### ISSUE TITLE
Issue cu al doilea aranjament de taste

### ISSUE THREAD

**Issue by nenominal** [SaltwaterC/romanian-programmers-mac#13]
Salut,

Am o tastatura cu un layout 2 (cel cu ~ intre z si shift). Cu toate ca aleg la rularea scriptului varianta 2 de layout, se instaleaza tot layout 1 (tasta ~ dintre z si shift devine "|\")

**Comment by SaltwaterC** [comment]
Salut,

Citește te rog discuția de la #6 privind pozițiile corecte în Romanian Pro. O să adaug un screenshot în README.md pentru a evita problema asta recurentă. Scopul Romanian Pro este să respecte pozițiie tastelor, nu pictogramele.

**Comment by SaltwaterC** [comment]
M-am uitat acum peste aranjamentul 1. Aranjamentul 1 e de fapt greșit implementat.

Deși personal am avut contact cu vreo 10 tastaturi Apple în ultimii 7 ani, toate folosesc numărul 2.

**Comment by nenominal** [comment]
Ok, nu e foarte clar nici din readme și nici din installer care este scopul alegerii layout-ului la instalare.
Acum am înțeles, mulțumesc.

**Comment by SaltwaterC** [comment]
Am îmbunătățit documentația și am reparat aranjamentul 1: https://github.com/SaltwaterC/romanian-programmers-mac/tree/dezvoltare
