### ISSUE TITLE
£ symbol

### ISSUE THREAD

**Issue by necenzurat** [SaltwaterC/romanian-programmers-mac#14]
Poti adauga si simbolul de **£** pe undeva pe tastatura?

**Comment by bogdanconstantinescu** [comment]
Aprob, avem programatori si "pă anglea".

**Comment by necenzurat** [comment]
e comic ca si @SaltwaterC e tot prin anglea, si nu a avut nevoie de £

**Comment by SaltwaterC** [comment]
Deja e rezolvată din moment ce sunt "pă anglea" de peste 3 ani și îmi iau salariul în £££.

https://github.com/SaltwaterC/romanian-programmers-mac/tree/non-standard/uk

**Comment by necenzurat** [comment]
Eventual pune si tu un link in readme la versiunea non-standard ca sa nu mai apara issue-uri dastea. Pupici.

**Comment by SaltwaterC** [comment]
@necenzurat: mno ai primit notificare de la GitHub dacă tot te-am menționat în commit message?

**Comment by necenzurat** [comment]
Da, dar cred ca trebuie sa platesc ceva, din principiu Ballmeresc.
![image](https://user-images.githubusercontent.com/145449/41287816-a5223bd0-6e4c-11e8-82cc-e6bb36effb30.png)
