### ISSUE TITLE
fn in loc de option

### ISSUE THREAD

**Issue by Jaymzu** [SaltwaterC/romanian-programmers-mac#15]
Salut, 

Cum as putea schimba modifierul din option in fn?

Thx

**Comment by madpipeline** [comment]
Instalează Ukelele, deschide aranjamentul în el și fă-ți de cap.

**Comment by SaltwaterC** [comment]
Exact ce a spus Ovidiu mai sus. Ukelele poate să remapeze tasta Fn, dar o să ai ceva de lucrat pentru că sunt foarte multe tabele datorită modificatorilor.
