### ISSUE TITLE
Punct zecimal numpad

### ISSUE THREAD

**Issue by overbog** [SaltwaterC/romanian-programmers-mac#17]
Punctul zecimal de pe numpad este "." nu "," cum ar trebui.

**Comment by SaltwaterC** [comment]
Numpad-ul a fost contribuit de către @SliMM. Nu pot confirma din păcate pentru că ultima dată pe când am folosit o tastatură Apple cu numpad a fost prin 2007. În prezent am acces la două MBP (2011 și 2017) și o tastatură compactă USB (A1242 - destul de rară de altfel).

**Comment by SaltwaterC** [comment]
Am aruncat o privire peste problemă.

Conform standardului pentru tasta respectivă:

> Pentru aranjamentul de caractere "Română", simbolul grafic generat de tastă la funcția birotică este virgula (0x002c).
> Pentru aranjamentul de caractere "Română (Programatori)", simbolul grafic generat de tastă la funcția birotică este punctul (0x002e).

Acest aranjament este "Română (Programatori)" nu "Română", deci punctul, nu virgula, este caracterul corect pentru tasta A53.
