### ISSUE TITLE
Have both layouts available simultaneously

### ISSUE THREAD

**Issue by MathPlayer** [SaltwaterC/romanian-programmers-mac#21]
Aș dori să pot instala separat și schimba între cele 2 layouts fără a fi nevoie de interacțiune cu conținutul acestui repository (+ logout / login).
Recent, am început să folosesc o tastatură externă cu layout diferit de cea default de la Apple.
Momentan, la fiecare switch de utilizare între tastatura macbook-ului și cea externă sunt nevoit să apelez din nou scriptul de instalare.

**Comment by SaltwaterC** [comment]
Momentan nu se poate folosind scriptul de instalare. Metodă semi-manuală:

```
git clone https://github.com/SaltwaterC/romanian-programmers-mac
cd romanian-programmers-mac
sudo rm "/Library/Keyboard Layouts/Romanian - Programmers.keylayout"
sudo cp "Romanian - Programmers 1.keylayout" \
"/Library/Keyboard Layouts/Romanian - Programmers 1.keylayout"
sudo cp "Romanian - Programmers 2.keylayout" \
"/Library/Keyboard Layouts/Romanian - Programmers 2.keylayout"
sudo find /System/Library/Caches -name "*IntlDataCache*" 2>/dev/null | sudo xargs rm -v
sudo find /var -name "*IntlDataCache*" 2>/dev/null | sudo xargs rm -v
```

Logout + Login. Asta va instala `Romanian Programmers 1` și `Romanian Programmers 2`, deci pot fi folosite amândouă.

**Comment by cipri-tom** [comment]
@MathPlayer și eu am problema asta, și am rezolvat-o cu Karabiner-elements, pe care îl folosesc oricum pentru alte customizări.
Și acolo poți selecta pe ce device se activează unele combinații, așa că am remapat tastele necesare doar pe unul din device-uri (astea fiind ~/` și §/° )
