### ISSUE TITLE
iPad Pro - 2nd Gen - ELI5 please - Cum instalez Romanian Programmers?

### ISSUE THREAD

**Issue by julianbr3** [SaltwaterC/romanian-programmers-mac#23]
Salutare. Dupa multe framantari interioare, dupa 23 ani de Windows, am trecut pe un iPad pro pentru acasa, relaxare si uneori pentru munca. Am cumparat si tastatura cover - transformandu-l intr-un laptop, sunt foarte fericit de achizitie. 

Insa ce imi lipseste foarte mult este tastatura Romanian Programmers - pur si simplu nu pot functiona in Romana fara acel aranjament.  Va multumesc foarte mult ca ati gandit deja la o solutie la acest disconfort MAJOR.  Lucrez cu texte, gasesc iPad excelent pana acum dar nu pot functiona fara diacritice. 

Problema mea e ca nu sunt Programator, habar n-am cum si ce sa fac. Ba mai mult, abia ma obisnuiesc cu Apple.

ELI5. Imi puteti va rog explica in pasi simpli cum instalalez cea mai buna si ergonomica tastatura romaneasca - Romanian Programmers? Exista vreun app pentru asa ceva? Multumesc frumos, din pacate fara diacritice! 

**tldr**: cum instalez Romanian Programmers keyboard pe iPad Pro 2nd Gen (2020)?

**Comment by SaltwaterC** [comment]
Bună. Nu am folosit vreodată iOS și nici nu știu dacă e posibil ca acest proiect să fie instalat pe iOS.

Dezvoltarea și utilizarea e făcută sub macOS.

**Comment by julianbr3** [comment]
Salut, merci de raspuns. Am incercat cu un app Keyman care are si Romanian Programmers. Total fail.

Ma gandesc ca odata cu aparitia tastaturilor hardware cover precum Smart Keyboard si Magic Keyboard (2020) poate cineva s-ar uita si la noi astia care s-au dus spre iPad pro cu tastatura fizica. Poate apar si altii cu solutii.

**Comment by julianbr3** [comment]
Am postat si aici, poate rezolva cineva acest puzzle. 

https://macforum.ro/t/romanian-programmers-keyboard-pentru-ipad-pro/4435

Slabe sanse se pare.
