### ISSUE TITLE
Vreo metodă suportată (sau alternativ ca hack) pentru a schimba între layout-uri?

### ISSUE THREAD

**Issue by BogdanSorlea** [SaltwaterC/romanian-programmers-mac#24]
Salut,

La instalare scriptul pune niște întrebări pentru a determina layout-ul tastaturii. Ideea e că pe laptop am un layout (tilda lângă tasta 1, nimic între shift-stânga și Z), iar tastatura bluetooth pe care o folosesc la birou are celălalt layout (§ lângă 1, tastă între shift-stânga și Z).
E vreo metodă cunoscută prin care să comut între ele, chiar și hack-ish - sau soluția ar fi să reinstalez de fiecare dată când trec de pe o tastatură pe alta? Mai e și problema că cere logout+login după install, ceea ce e destul de agasant

Thx.

**Comment by SaltwaterC** [comment]
Bună. Pot fi instalate ambele aranjamente simultan, atâta timp cât au nume distincte.

```bash
sudo cp "Romanian - Programmers.icns" "/Library/Keyboard Layouts/"
sudo cp "Romanian - Programmers 1.keylayout" "/Library/Keyboard Layouts/Romanian - Programmers 1.keylayout"
sudo cp "Romanian - Programmers 2.keylayout" "/Library/Keyboard Layouts/Romanian - Programmers 2.keylayout"
sudo find /System/Library/Caches -name "*IntlDataCache*" 2>/dev/null | sudo xargs rm -v
sudo find /var -name "*IntlDataCache*" 2>/dev/null | sudo xargs rm -v
```

Ar trebui să poți alege manual între 1 și 2 în funcție de situație. Deasemenea: [#21](https://github.com/SaltwaterC/romanian-programmers-mac/issues/21#issuecomment-597377537)
