### ISSUE TITLE
Nu functioneaza pe Monterey 12.3.1

### ISSUE THREAD

**Issue by vilie** [SaltwaterC/romanian-programmers-mac#25]
Pare ca nu functioneaza pe Monterey.

https://discussions.apple.com/thread/253353282

Pare ca ar fi instalate unde trebuie. Mai investighez

```
valentini@valhalla ~ % ls /Library/Keyboard\ Layouts 
Romanian - Programmers.icns		Romanian - Programmers.keylayout
```

**Comment by SaltwaterC** [comment]
Ciudat. Mașina curentă a venit cu Monterey, dar am instalat mai devreme de 12.3.1.

![monterey](https://i.imgur.com/Obb9wqe.png)

Ai dat logout/login?

**Comment by vilie** [comment]
Am dat. Si logout/login si restart. Am acelasi setup (M1 Pro).
Poti confirma ca la tine merge pe 12.3.1? Daca da, banuiesc ca se poate inchide tichetul (o fi de la mine).

**Comment by SaltwaterC** [comment]
Scriu cu diacritice de pe această mașină, de unde și surpriza. Este posibil ca o problemă să fi apărut ulterior. O să încerc mai pe seară după ce termin cu munca să văd dacă pot re-crea problema dacă dezinstalez aranjamentul și instalez pe curat sub 12.3.1.

Încă nu închid până nu mă lămuresc de unde-i problema.

**Comment by vilie** [comment]
Era de la mine, din cauza unor restricții de la laptopul de muncă. Îmi merge acum. Scuze de deranj. Apreciez foarte mult munca pe are o faci :-)

**Comment by SaltwaterC** [comment]
@vilie mulțumesc frumos pentru confirmare și apreciere. Nu am putut reproduce, dar o să rămână ca posibilă sursă de probleme pentru posteritate. Până acum nu am întâlnit în practică probleme legate de device management, deși folosesc mașini cu management de vreo câțiva ani.

**Comment by ancabanca123** [comment]
Mie îmi mergea bine pe Monterey dar acum am schimbat laptopul și am Apple Silicon tot Monterey. Am instalat fără probleme layoutul dar de cele mai multe ori nu reușesc să fac switch pe el. A mai pățit cineva? Și aveți idee ce pot să îi fac să meargă?

<img width="249" alt="image" src="https://user-images.githubusercontent.com/31069226/178954590-5670015f-6888-4671-a399-3c8191b1fa25.png">

**Comment by SaltwaterC** [comment]
A funcționat de la prima instalare fără nici o problemă. Ce-i drept, nu schimb niciodată de pe Romanian Pro pentru că pot scrie în alte limbi fără probleme.

![kbd](https://i.imgur.com/z5X2P9k.png)

**Comment by ancabanca123** [comment]
Mulțumesc pentru răspuns. Am mai instalat o dată și acum îmi merge. Nici eu nu folosesc altă limbă de obicei, dar nu reușisem să o scot pe cealaltă pentru că nu îmi mergea switchul.
