### ISSUE TITLE
Alt+G pentru £ (GBP)

### ISSUE THREAD

**Issue by DATEx2** [SaltwaterC/romanian-programmers-mac#28]
Ar fi extrem de util!

**Comment by SaltwaterC** [comment]
[Este deja](https://github.com/SaltwaterC/romanian-programmers-mac?tab=readme-ov-file#despre) in ramura [non-standard/uk](https://github.com/SaltwaterC/romanian-programmers-mac/tree/non-standard/uk). Locuiesc în UK, deci viața fără £ ar fi dificilă.
