### ISSUE TITLE
Cand aleg tastatura cu numarul 2 imi instaleaza cea cu numarul 1

### ISSUE THREAD

**Issue by nikini** [SaltwaterC/romanian-programmers-mac#6]
Fie descrierea e gresita, fie optiunea e invers. Daca aleg tastatura 2 care zice ca semnul "±" e in stanga cifrei 1 atunci imi instaleaza o tastatura care are in stanga tastei "Z" un slash (sau backslash)

**Comment by nikini** [comment]
Citez:

> » Primul aranjament are tasta inscriptionata cu "` si ~" inainte de 1
» Al doilea aranjament are tasta inscriptionata cu "§ si ±" inainte de 1

Eu am ales tastatura 2 si o pune pe prima. Apoi am ales tastatura 1 si mi-a instalat corect

**Comment by SaltwaterC** [comment]
Apple nu are un standard pentru aranjament și nici documentație. Până acum, aranjamentul 2 funcționează pe mașinile cu care am avut de-a face: MBA 2011 (RO spec), MBA 2012 (US spec), MBA 2013 (RO spec), MBP 2014 (UK spec). Aranjamentul 1 a fost contribuit de către Cristian iar detaliile le-am stabilit după lungi discuții și experimente folosind [Key Codes](https://manytricks.com/keycodes/).

"\|" în stânga lui Z pentru aranjamentul 2 e corect atât pentru Romanian Programmers cât și pentru [aranjamentul primar](https://en.wikipedia.org/wiki/Romanian_keyboard_layout) așa cum este corect și "`~" în stânga lui 1.

Aranjamentele oferite de către acest proiect au ca scop pozițiie corecte pe tastatură *conform SR 13392:2004*, poziții care din motive evidente nu corespund cu pictogramele.

**Comment by nikini** [comment]
Am verificat pe rMBP 13, 15, mba, tastatura apple cu fir si tastatura apple fara fir. Toate au in stanga lui z "`~" si sunt tastaturi internationale. Banuiesc ca romanian programmer keyboard pleaca de la o tastatura internationala, nu una UK, US sau RO...

**Comment by SaltwaterC** [comment]
Tastaturile RO, US, cât și cea UK de pe care tastez acum au backtick-tilda ca pictogramă în stânga lui Z, dar funcționează pe post de backslash-pipe. De fapt, tastatura UK nu prea corespunde la capitolul pictograme. Spre exemplu, pe 3 am 3-£ (£ e caracter care nu există în SR 13392:2004) dar funcționează pe post de 3-# (US, Romanian Pro).

Romanian Programmers este construit peste un aranjament standard US + taste de modificare pentru diacritice, de unde și ideea de Programmers - am scris cod de când mă știu pe tastaturi US.

De fapt, nu folosesc deloc tasta din stânga lui Z pentru că în general nu se găsește pe tastaturile pe care le folosesc sub Windows / Linux. Dar conform lui Secărică, dacă există, atunci e backslash-pipe.

**Comment by nikini** [comment]
Si eu asta zic. Ca ea nu exista pe tastatura US dar exista pe tastatura internationala. Scrie si pe wikipedia asta:

https://en.wikipedia.org/wiki/QWERTY#Apple_International_English_Keyboard
