### ISSUE TITLE
Tastatura cu al doilea aranjament nu are caracterul "±" sau "§"

### ISSUE THREAD

**Issue by nikini** [SaltwaterC/romanian-programmers-mac#7]
>» Primul aranjament are tasta inscriptionata cu "` si ~" inainte de 1
» Al doilea aranjament are tasta inscriptionata cu "§ si ±" inainte de 1

Dupa ce am instalat al doilea aranjament, cand apas pe tasta din stanga cifrei 1 imi scrie "` si ~". Poate are ceva de-a face cu [asta](https://github.com/SaltwaterC/romanian-programmers-mac/issues/6), pentru ca mai intai am instalat un aranjament (care din cauza textului, sau a respectivului bug a fost instalat gresit) apoi pe al doilea.

**Comment by SaltwaterC** [comment]
Am explicat în #7 scopul implementării.
